
version: '3.8'

services:
  some-postgres:
    image: postgres:14
    container_name: some-postgres
    environment:
      POSTGRES_DB: db_ecom
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    depends_on:
      - some-postgres

volumes:
  postgres_data:
